# Generated by Django 3.0.2 on 2020-01-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
