# Generated by Django 3.0.2 on 2020-01-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0002_subscribers_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
